### ISSUE TITLE
load tabs bypassing chrome cache

### ISSUE THREAD

**Issue by tortino** [hrj/sloth#12]
when I click on a tab it is loaded from browser cache.
Instead I want to see the newest version of the page, not an old one from the browser cache.
At the moment, when I click on a tab, I have to hit the refresh button to get the latest version of every page, and it's annoying.
Is it possible to add an option to auto reload the tab, bypassing the cache?
thanks.

**Comment by GarethPW** [comment]
I'm pretty sure this is actually a bug with Chrome. But it would probably be possible to fix using the extension.

**Comment by hrj** [comment]
@tortino 

* is the problem happening because of this extension?
* is it happening for a particular website or all websites?

---
@GarethPW If it's a general problem with Chrome, then working around that in an extension is going to be flaky and I would rather not implement that.

**Comment by tortino** [comment]
Hello hrj,
it's not happening because of your extension, and it happens for all web sites.

I don't know if it is a bug or not.
maybe google want to give the impression that restoring session is fast, so it reloads pages from cache.

with a web search I have found this api, that seems to be useful.
https://developer.chrome.com/extensions/tabs#method-reload
(there is a bypassCache parameter)

**Comment by tortino** [comment]
I have found a somewhat relevant bug, if I understand this correctly (I'm not sure):
https://bugs.chromium.org/p/chromium/issues/detail?id=828492&q=component%3AUI%3EBrowser%3ESessions&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified
reading the comments it seems to me that restoring session is done deliberately by using cache :-(

**Comment by GarethPW** [comment]
@tortino That seems like the right issue report. It's *technically* not a bug, but it's not the behaviour I think most would expect.

Although a fix could be implemented in the extension, as @hrj said, such a feature would not really be appropriate.
