### ISSUE TITLE
Add Option to "not read all new background tabs"

### ISSUE THREAD

**Issue by Noah1995** [hrj/sloth#14]
Please add the all  background new tabs  don't read to Option....

**Comment by Noah1995** [comment]
And it's best to achieve this feedback...[Lazy Tabs](https://chrome.google.com/webstore/detail/lazy-tabs/aabgbgciohhaogajcnacpgilhmacdahc)
![【2020-02-04】【08∶05∶06】](https://user-images.githubusercontent.com/25548230/73701617-13d04600-4725-11ea-8572-b3fd5906a636.jpg)

**Comment by hrj** [comment]
I changed the title to reflect my understanding of your request. But I am not very sure I have understood correctly.

What does this have to do with "Lazy tabs"? Are you facing the same issue with Sloth? Sloth doesn't load and then unload the tab, so I am not sure how the review of "Lazy tabs" is relevant.

**Comment by Noah1995** [comment]
![【2020-02-04】【11∶41∶54】](https://user-images.githubusercontent.com/25548230/73711940-7b958980-4743-11ea-81c3-0b74c8e80a46.jpg)
I use the translation expansion...
like this pic...
but  Tab Suspender  Some pages don't seem to block loading...
I want all newly opened background tabs to be automatically blocked after displaying icons and titles...

**Comment by hrj** [comment]
> I want all newly opened background tabs to be automatically blocked after displaying icons and titles...

This is the main purpose of the `Sloth` extension, and it works fine for me. What does not work for you *in Sloth*?

And BTW, there is no loading and unloading of tabs in `Sloth`. Perhaps you are getting confused with some other extension.

**Comment by hrj** [comment]
Oh ok, I understand now, what you are saying. When you open a new background tab by *manually clicking a link*, you want it to open in suspended state.

This would be nice, but it is not something on the roadmap for `Sloth` so I am going to close this issue.

**Comment by Noah1995** [comment]
ok...

What does it mean to end this  issue.?

Are you willing to add it?

**Comment by hrj** [comment]
> Are you willing to add it?

No, not by myself. However, if someone else does the coding and makes a pull-request, I can look into it.
