### ISSUE TITLE
Is there any plan for putting this up on Chrome store?

### ISSUE THREAD

**Issue by akilan27** [hrj/sloth#2]
Also paging @xftroxgpx who led me to this extension. If neither of you want to do it, I can.

**Comment by hrj** [comment]
Thanks for your interest @akilan27 

I was waiting for users to confirm that it works for them. I have now submitted it to the chrome store.

Will put the URL here once the store publishes it.

**Comment by hrj** [comment]
Available [here](https://chrome.google.com/webstore/detail/sloth/filkeckmpdjogddcamkafnekhgfaehkc?hl=en-US&gl=IN)!

**Comment by akilan27** [comment]
Thanks. :)

**Comment by hrj** [comment]
@akilan27 Are you able to install via that link?

When I try to install, it gives an error, but that maybe because I have a weird browser setup.

**Comment by akilan27** [comment]
Yes, I can install. And I'm using it now from webstore install only.
