### ISSUE TITLE
Feature request : Option to disable new tab feature

### ISSUE THREAD

**Issue by syaifulnizamyahya** [hrj/sloth#3]
I have multiple open window. Each window is opening its own new tab. It is annoying to have to close each of this autogenerated new tab.

An option to disable this feature would be nice.

Thanks.

**Comment by hrj** [comment]
Implemented this option in 440561e1d1eac39f3e67a9ed3b38e2a9f0a07e74

Will be available in version 0.2, which I am publishing right away.
