### ISSUE TITLE
option to mark all background tabs as inactive when clicking the sloth button

### ISSUE THREAD

**Issue by fletom** [hrj/sloth#8]
this extension is amazing. it's a night and day difference when trying to use Chrome with 8 GB of memory and bad tab habits

a small feature request: sometimes a Chrome browsing session is getting way too heavy, it would be great to have an option to reset all the open tabs without having to quit and restart chrome to do so. I think it should be relatively easy to do this when clicking the toolbar button, which as far as I can tell doesn't have any action associated with it

thanks!

**Comment by hrj** [comment]
That's a great idea. Will try to implement this weekend.

**Comment by hrj** [comment]
Implemented in v0.3.

Thanks for the idea @fletom
